OWASP/Python-Honeypot

- core/network.py
fixing issue #6, @dhirensr it would be great if you can send me your review on this. thanks.
> fix issue #6 ignoring container.

- api/server.py
- config.py
- core/network.py
- database/connector.py
save real machine IP address as the destination of the attack in events.
> targeted machine IP address

- .travis.yml
- config.py
- core/load.py
incase if you want to add module in same category parallel, it will increase the reserved port and setup the machine (e.g. ssh:22, ssh:23, ...)
> port reservation (auto increase)

- api/server.py
- config.py
> use api without auth

- .travis.yml
- core/load.py
- lib/modules/ics/__init__.py
test switch for travis-ci and/or testing new modules.
> add test switch

- api/server.py
as discussed with Ali on ticket https://github.com/zdresearch/OWASP-Honeypot/issues/15
@Ali-Razmjoo : please review this also on weekend
> added two new routs top honeypotevent/network events machine names.

- api/server.py
- database/connector.py
Related to :=
https://github.com/zdresearch/OWASP-Honeypot/issues/7
https://github.com/zdresearch/OWASP-Honeypot/pull/9
> Top network/honeypot events ip by country 

- api/server.py
what : usage
http://127.0.0.0:5000/api/events/top_network_ips_by_country_by_date?country=DE&date=2019-02-24
related to :
https://github.com/zdresearch/OWASP-Honeypot/issues/22
> added new routes top honeypot/network events by country and date

- api/server.py
what : remove the todos as the docs are already added to wiki
> removed all the todo's add docs to wiki

- api/server.py
usage : 
http://127.0.0.1:5000/api/events/top_network_ports_by_country?country=DE&date=2019-02-24
http://127.0.0.1:5000/api/events/top_network_ports_by_country?country=DE
Related to : https://github.com/zdresearch/OWASP-Honeypot/issues/24
> added new routes for honeypot/network events top ports by country /&by date

- api/database_queries.py
- api/server.py
- web/static/js/main.js
what : the groupby conditions was different for ports routes with date and with
country and it can be refactored as in ips routes
> refactored code for honeypot/network events ports

- core/alert.py
> fix error in stdout + fix style

- core/load.py
- database/connector.py
- lib/modules/ftp/strong_password/__init__.py
- lib/modules/ftp/weak_password/__init__.py
- lib/modules/http/basic_auth_strong_password/__init__.py
- lib/modules/http/basic_auth_weak_password/__init__.py
- lib/modules/ics/veeder_root_guardian_ast/__init__.py
- lib/modules/ssh/readme.md
- lib/modules/ssh/strong_password/Dockerfile
- lib/modules/ssh/strong_password/__init__.py
- lib/modules/ssh/strong_password/files/ssh_listener.py
- lib/modules/ssh/weak_password/__init__.py
@Ali-Razmjoo : added the script file!
there are 2 problems now: 
1. script needs an ssh key : i don't know why it is getting deleted in docker container ,this issue can be solved by using password also i think.
2. the other issue is we need to forward requests coming on ssh port on server(docker container) to some other port as mentioned in the script and then script will log the information.
Then we can read from docker host by accessing the file.
also https://docs.docker.com/network/iptables/ is useful for understanding how docker manages packet forwarding between dockerhost and containers.
the easy to forward would be : 
/sbin/iptables -A PREROUTING -t nat -p tcp --dport 22 -j REDIRECT --to-port 2222 
but it doesn't work and so would like you to take a look please.
> added a script in ssh module and also made some changes in ssh dockerfile

- core/load.py
- database/connector.py
what : after every 1minute the events will get inserted in bulk and when pressen
ctrl+c the remaining events will get inserted in bulk
related to : https://github.com/zdresearch/OWASP-Honeypot/issues/43
> mongodb bulk adding code

- api/database_queries.py
- api/server.py
- web/static/index.html
- web/static/js/main.js
new web routes for credential events
> added new creds routes like top usernames,passwords 

- .travis.yml
- core/_die.py
- core/get_modules.py
- core/load.py
- database/connector.py
- ohp.py
* container and image name
* faster api update
* fix thread issue
* add python 3.8 and 2.7 to ci
> enhancements - mainly thread handling

- .travis.yml
- requirements-dev.txt
- requirements.txt
couldn't access to #55 to send this fix.
> making changes with travis bot for testing env #55

- config.py
- core/load.py
- core/network.py
* fix stdout capturing
* update honeypot port filtering
* added tshark health checker
* add localhost test feature
> enhancement packet capturing and db

- .travis.yml
@Ali-Razmjoo : we are wanting to create a testing environment in https://github.com/zdresearch/OWASP-Honeypot/pull/53 so we want to run pytest after every PR and ensure tests are passing.
> added pytest command which should be run after every PR

- api/database_queries.py
- api/server.py
- config.py
- core/compatible.py
- core/load.py
- core/network.py
- database/connector.py
- lib/modules/ftp/strong_password/__init__.py
- lib/modules/http/basic_auth_strong_password/__init__.py
- lib/modules/ssh/strong_password/__init__.py
- requirements.txt
- web/static/js/main.js
fix for #64 - I guess API needs to be updated....
> work in progress: specifying ip_dest, port_dest, ip_src, port_src

- core/alert.py
- core/compatible.py
- core/load.py
- core/network.py
- database/connector.py
Displays packet information in real time on the terminal. Related to issue #68
> Enhanced verbose output 

- core/network.py
old style ip.dst isn't working on macos anymore, and variable _ doesn't exist anymore.
> tshark starter bug fixed

- core/load.py
related to https://github.com/zdresearch/OWASP-Honeypot/issues/107
> fixing the message format which had slashes.

- .github/workflows/python-app.yml
- CONTRIBUTING.md
@ChakshuGupta's doc PR was against development so this is the final PR against master.
> updating contributing.md and added test instructions

- .github/workflows/python-app.yml
- core/compatible.py
related to https://github.com/zdresearch/OWASP-Honeypot/issues/118
> fix tmp thread naming.

- core/compatible.py
- tests/test_core_compatible.py
the generate token function  was not using the length arg
> fix bug in generate token.

- core/compatible.py
> fix naming the dir

- modules/ftp/strong_password/Dockerfile
- modules/http/basic_auth_strong_password/Dockerfile
- modules/http/basic_auth_weak_password/Dockerfile
- modules/ssh/strong_password/Dockerfile
- modules/ssh/weak_password/Dockerfile
> remove unnecessary packages

- .github/workflows/python-app.yml
- Dockerfile.api
- config.py
- core/compatible.py
- core/file_monitor.py
- core/load.py
- core/network.py
- docker-compose-host-ci.yml
- docker-compose.yml
- requirements-dev.txt
- requirements.txt
replace docker daemon instead of nohup, this way we can also test our docker to be updated.
> Involve docker to tests + use proper daemon

- requirements.txt
> Fix Watchdog version

- config.py
- core/alert.py
- core/log.py
Related to https://github.com/zdresearch/OWASP-Honeypot/issues/92
what: 1. core.log was missing and hence I added the log functionality.
@Ali-Razmjoo : I tried to borrow from https://github.com/zdresearch/OWASP-Nettacker/blob/master/core/log.py
I didn't think the language is useful for use in log_in_file because we are displaying the log in console in info and verobse_info anyways. hence removed few parts
> added logging functions in core.log

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/shiftleft-analysis.yml
> add code scan

- web/static/index.html
- web/static/js/main.js
> enhance webui

- .github/workflows/ci.yml
> Fix GitHub action

- modules/smtp/strong_password/files/smtpd_server/secure_smtpd/smtp_channel.py
Reverts OWASP/Python-Honeypot#212
> Revert "Fix multiple import"

- lib/ip2location/IP2Location.py
- modules/ssh/strong_password/files/ssh_listener.py
- tests/test_core_alert.py
While browsing through the Code and studying it for better understanding, I found minor bugs and anti-patterns that can be possibly improved to mitigate any potential bug. Since this is the first time, when I'm contributing to OWASP, I wanted to get a better understanding of the Codebase and make contributions on the same. 
The following commits have been made on the Codebase: 
- Fixed no use of `self`
Some of the methods are not using its bound instance, so I have added a `@staticmethod` decorator. From the perspective of saving memory and computation, they are more efficient as Python does not have to instantiate a bound method for every instance of the class.
> Fixed no use of self

- .github/workflows/ci.yml
- core/load.py
- modules/ftp/strong_password/Dockerfile
- modules/ftp/strong_password/files/requirements-apt-get.txt
- modules/ftp/weak_password/Dockerfile
- modules/ftp/weak_password/files/requirements-apt-get.txt
- modules/http/basic_auth_strong_password/Dockerfile
- modules/http/basic_auth_strong_password/files/requirements-apt-get.txt
- modules/http/basic_auth_weak_password/Dockerfile
- modules/http/basic_auth_weak_password/files/requirements-apt-get.txt
- modules/ics/veeder_root_guardian_ast/Dockerfile
- modules/ics/veeder_root_guardian_ast/files/requirements-apt-get.txt
- modules/smtp/strong_password/Dockerfile
- modules/smtp/strong_password/files/requirements-apt-get.txt
- modules/ssh/strong_password/Dockerfile
- modules/ssh/strong_password/files/requirements-apt-get.txt
- modules/ssh/weak_password/Dockerfile
- modules/ssh/weak_password/files/requirements-apt-get.txt
until this apt-get requirement auto update is not fix, we can't use it... must of the packages got old and removed from ubuntu repos.
> fix broken module #245

- web/static/js/explore.js
> Fix issue when 0 log records are returned from the api

- api/database_queries.py
- database/connector.py
- database/datatypes.py
- readme.md
Updating docs and readme file with appropriate information.
> Updating docs and readme

- web/static/css/style.css
- web/static/index.html
- web/static/js/explore.js
> Improve error handling in log explorer.

- api/server.py
Fixing all event count. Fixes issue #291
> Fix all record count

- api/server.py
- requirements.txt
Partially solves #310 
Docs added for 
Swagger ui can be checked from - `/api/docs`
> adding docs and swagger configuration

- core/compatible.py
- core/load.py
- database/connector.py
If elasticsearch server is not running. This error is produced. It is because a part of code is executed before starting of the server which uses elasticsearch client .
After fixing it
> show error - cannot connect to elasticsearch

- config.py
- core/alert.py
- core/color.py
- core/compatible.py
- core/exit_helper.py
- core/load.py
- core/logo.py
- core/token.py
- modules/ftp/strong_password/__init__.py
- modules/http/basic_auth_strong_password/__init__.py
- modules/smtp/strong_password/__init__.py
- modules/ssh/strong_password/__init__.py
- tests/test_core_compatible.py
There were 4 cyclic dependency, I removed 3 of them
#346 
I tested it on my machine it is working
> remove cyclic dependency

- .github/workflows/ci.yml
- core/load.py
in case something failed we can debug it
> add container debugging in verbose mode

- api/server.py
fix the API URL, which was hardcoded
#351
> fix API URL

- core/alert.py
- core/load.py
Add verbose logging
Tested Locally
> enable verbose logging

- config.py
- ohp.py
- requirements.txt
Add sentry monitoring
Sentry helps us to monitor, debug bugs is our code by alerting and providing various details. Example given below - 
I turned off local elasticsearch server and sentry notified me about the bug:
- [ x The code has been thoroughly tested in my local development environment with flake8 and pylint.
> add sentry monitoring

- core/load.py
> fix-module-shutting
